services:
  database:
    image: mysql:8
    container_name: sgu-database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db-users
    ports:
      - "3307:3306"
    volumes:
      - sgu-volume:/var/lib/mysql
    networks:
      - sgu-net
    restart: unless-stopped

  frontend:
    image: client:1.0-sgu
    build: 
      context: ./client
      dockerfile: Dockerfile
      args:
        API_HOST: localhost
        API_PORT: 8081
        API_BASE: /api/usuarios/
    container_name: sgu-frontend
    ports:
      - "3000:80"
    networks:
      - sgu-net
    restart: unless-stopped
    depends_on:
      - database


  backend:
    image: server:1.0-sgu
    build: ./server
    container_name: sgu-backend
    environment:
      SERVER_PORT: 8080
      DB_HOST: database
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: db-users
    ports:
      - "8081:8080"
    depends_on:
      - frontend
    networks:
      - sgu-net

volumes:
  sgu-volume:
    external: true

networks:
  sgu-net:
    external: true